### ISSUE TITLE
[Bug]:  Using the 360p project, the screen will appear blurry after downloading the image

### ISSUE THREAD

**Issue by lizhaoming634** [goodix-ble/GR5526.SDK#24]
### The Branch/Version

master

### What happened?

Burn a 360p project, then download the image resources and freeze the screen

#define ENABLE_4BYTES_ADDRESS_MODE        0u      /* SET 1 IF USING 4-Byte Address NorFlash */
Set this macro definition to 0 and it will display normally

### Expected Result

The screen displays the correct image

**Comment by nixlong** [comment]
can you take a video to show the bug ?

**Comment by lizhaoming634** [comment]
![image](https://github.com/user-attachments/assets/25a88ef6-a2ab-4127-92ef-c174dbdb04d0)
if ENABLE_4BYTES_ADDRESS_MODE is 1, i download the firmware and image resourse, It doesn't display the image correctly

https://github.com/user-attachments/assets/58beaa2b-aa99-497f-ac94-9e57d66b52b5

**Comment by lizhaoming634** [comment]
![image](https://github.com/user-attachments/assets/2650e97f-d1f5-4f50-8cc2-a68abae0b186)

https://github.com/user-attachments/assets/16c9cef0-12d9-45c7-8d97-a6a881613b90

When I changed ENABLE-4BYTES_SDDRESS.MODE to 0, other pages were normal, but the message page was not displaying properly
